minecraft.version.major = 26.2
minecraft.version.title = 26.2
minecraft.version.supported = 26.2-pre-2

fabric.loom = plain

fabric.api.key_mapping_module = fabric-key-mapping-api-v1

#mixins.extra = amecs_key_modifiers.compat.controlling.mixins.json

preprocessor.mc_version_number = 260200
#preprocessor.controlling_integration =
