minecraft.version.major = 1.21
minecraft.version.title = 1.21.9-1.21.10
minecraft.version.supported = 1.21.9, 1.21.10

fabric.loom = remap

fabric.api.key_mapping_module = fabric-key-binding-api-v1

mixins.extra = amecs_key_modifiers.compat.controlling.mixins.json

preprocessor.mc_version_number = 12109
preprocessor.controlling_integration =
