[versions]
amecsApi = "1.6.2"
fabric-api = "0.83.0+1.20"
java = "17"
minecraft = "1.20"
nmuk = "1.2.0"

[libraries]
amecsApi = { group = "de.siphalor.amecs-api", name = "amecs-api-mc1.20.0", version.ref = "amecsApi" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
nmuk = { group = "de.siphalor.nmuk", name = "nmuk-mc1.20.0", version.ref = "nmuk" }
