[versions]
changelogPlugin = "2.5.0"
fabric-loader = "0.18.4"
jcyo = "0.6.0"
licenser = "2.2.2"
lombok = "1.18.44"
modPublisher = "2.1.8"

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelogPlugin" }
jcyo = { id = "de.siphalor.jcyo", version.ref = "jcyo" }
licenser = { id = "dev.yumi.gradle.licenser", version.ref = "licenser" }
modPublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modPublisher" }

[libraries]
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

