minecraft.version.major = 1.21
minecraft.version.title = 1.21.3-1.21.5
minecraft.version.supported = 1.21.3, 1.21.4, 1.21.5

fabric.loom = remap

fabric.api.key_mapping_module = fabric-key-binding-api-v1

mixins.extra = amecs_key_modifiers.compat.controlling.mixins.json

preprocessor.mc_version_number = 12103
preprocessor.controlling_integration =
