on:
  push:
    branches:
      - "1.16"


jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fix language file names
        run: |
          for lang in src/main/resources/assets/*/lang/*.json
          do
            rename=$(echo "$lang" | sed -e 's/\b\w\+\.json$/\L\0/' -e 's/\b\([a-z]\+\)\.json$/\/\1_\1.json/')
            mv "$lang" "$rename" || true
          done

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'src/main/resources/assets'
          default_author: github_actions
          message: Fix language file names
